import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, CircleHelp, Download, RefreshCw, Search, ShieldCheck } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from './api';
import type { Band, Deviation, SiteRisk } from './types';

const bands: Record<Band, string> = { CRITICAL: 'Review first', HIGH: 'Needs attention', MEDIUM: 'Keep watching', LOW: 'Routine review' };
const levels = { MAJOR: 'Major · safety or data concern', MINOR: 'Minor · protocol mismatch', ADMINISTRATIVE: 'Administrative · documentation' };
const titles: Record<string, string> = { MISSED_VISIT: 'A scheduled visit was missed', OUT_OF_WINDOW: 'A visit was outside its allowed dates', DOSE_ERROR: 'The recorded dose does not match the protocol', WRONG_ROUTE: 'Medicine was given by a different route', BANNED_MEDICATION: 'A prohibited medicine was recorded', MISSING_ASSESSMENT: 'A required assessment is missing' };
const actions: Record<string, string> = { MISSED_VISIT: 'Ask the site team to follow up and document why the visit was missed.', OUT_OF_WINDOW: 'Review the visit dates and document the impact of the delay.', DOSE_ERROR: 'Ask the investigator to assess the dose record and any safety impact.', WRONG_ROUTE: 'Ask the investigator to review administration and participant safety.', BANNED_MEDICATION: 'Ask the medical monitor to review the medication record.', MISSING_ASSESSMENT: 'Confirm whether the assessment was completed or needs follow-up.' };
const country: Record<string, string> = { US: 'United States', CA: 'Canada', GB: 'United Kingdom', DE: 'Germany', IN: 'India', AU: 'Australia', BR: 'Brazil', JP: 'Japan' };

export default function App() {
  const [sites, setSites] = useState<SiteRisk[]>([]);
  const [issues, setIssues] = useState<Deviation[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [page, setPage] = useState<'overview' | 'issues' | 'help'>('overview');
  const [selected, setSelected] = useState('');
  const [search, setSearch] = useState('');
  const [band, setBand] = useState('');
  const [severity, setSeverity] = useState('');
  const [siteFilter, setSiteFilter] = useState('');
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [ascending, setAscending] = useState(false);
  const [limit, setLimit] = useState(12);
  const [busy, setBusy] = useState('');
  const [notice, setNotice] = useState('');
  async function load() {
    setLoading(true); setError('');
    try { const [s, d] = await Promise.all([api.risks(), api.allDeviations()]); setSites(s); setIssues(d); }
    catch { setError('We could not load your trial data. Check that the local server is running, then try again.'); }
    finally { setLoading(false); }
  }
  useEffect(() => { void load(); }, []);
  useEffect(() => { setLimit(12); }, [selected, page, search, band, severity, siteFilter, from, to]);
  const ranked = useMemo(() => sites.filter(s => (!band || s.band === band) && (s.site_name + s.site_id + (country[s.country] || s.country)).toLowerCase().includes(search.toLowerCase())).sort((a, b) => ascending ? a.score - b.score : b.score - a.score), [sites, search, band, ascending]);
  const site = sites.find(s => s.site_id === selected);
  const visibleIssues = issues.filter(d => (!selected || d.site_id === selected) && (!siteFilter || d.site_id === siteFilter) && (!severity || d.severity === severity) && (!from || d.detected_at.slice(0, 10) >= from) && (!to || d.detected_at.slice(0, 10) <= to));
  const attention = sites.filter(s => ['HIGH', 'CRITICAL'].includes(s.band)).length;
  const major = issues.filter(d => d.severity === 'MAJOR').length;
  function navigate(next: typeof page) { setPage(next); setSelected(''); setSeverity(''); setSiteFilter(''); setFrom(''); setTo(''); setLimit(12); }
  function openSite(id: string) { navigate('overview'); setSelected(id); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async function report(id: string) {
    setBusy(id); setNotice('');
    try { await api.capa(id); setNotice('Your draft action plan has been downloaded. Review it with the investigator or quality team.'); }
    catch { setNotice('The action plan could not be created. Please try again.'); }
    finally { setBusy(''); }
  }
  const issueCards = <><div className="issue-list">{visibleIssues.slice(0, limit).map(d => <article className="issue" key={d.id}>
    <div className="issue-top"><span className={'badge ' + d.severity}>{levels[d.severity]}</span><span>{d.site_id} · {d.detected_at.slice(0, 10)}</span></div>
    <h3>{titles[d.kind] || d.kind.replace(/_/g, ' ').toLowerCase()}</h3>
    <p>{d.description}</p><div className="next-action"><strong>Suggested next step</strong><p>{actions[d.kind] || 'Ask the quality team to review and document this finding.'}</p></div>
    <div className="issue-bottom"><details><summary>Evidence & protocol details</summary><p><strong>Rule:</strong> {d.protocol_clause}</p><p>{d.rationale}</p><p>Participant {d.patient_id} · Visit {d.visit_id}</p><p>{d.source === 'LLM' ? 'AI-assisted finding — requires review' : 'Detected by a protocol rule'} · Confidence {Math.round(d.confidence * 100)}%</p></details><button className="secondary" disabled={!!busy} onClick={() => void report(d.id)}><Download size={16}/>{busy === d.id ? 'Creating plan…' : 'Download action plan'}</button></div>
  </article>)}</div>{!visibleIssues.length && <div className="empty">No issues match these filters. Try another site or a wider date range.</div>}{visibleIssues.length > limit && <button className="secondary more" onClick={() => setLimit(n => n + 12)}>Show 12 more issues</button>}</>;
  return <div className="app-shell">
    <header className="app-header"><a className="brand" href="#" onClick={e => { e.preventDefault(); navigate('overview'); }}><ShieldCheck size={28}/><span>TrialSutra<small>Spot issues. Understand risk. Take action.</small></span></a><span className="demo-label">Demo · fictional data only</span><button className="icon-button" disabled={loading} onClick={() => void load()} aria-label="Refresh data"><RefreshCw size={18}/></button></header>
    <nav className="nav-tabs" aria-label="Main navigation"><button aria-current={page === 'overview' ? 'page' : undefined} onClick={() => navigate('overview')}>Overview</button><button aria-current={page === 'issues' ? 'page' : undefined} onClick={() => navigate('issues')}>All issues</button><button aria-current={page === 'help' ? 'page' : undefined} onClick={() => navigate('help')}><CircleHelp size={16}/>How to use</button></nav>
    <main className="main-content">
      {error && <div className="error" role="alert">{error}<button onClick={() => void load()}>Try again</button></div>}
      {notice && <div className="notice" role="status">{notice}<button onClick={() => setNotice('')} aria-label="Dismiss message">×</button></div>}
      {page === 'help' ? <><div className="page-heading"><p className="eyebrow">START HERE</p><h1>Your trial, one step at a time.</h1><p>This tool compares recorded patient visits with the trial's rules and helps you decide where to review first.</p></div><div className="guide-grid">{[['1', 'Find a site to review', 'A site is a research center. Start with “Review first” sites on Overview; they have the highest calculated risk.'], ['2', 'Understand the issue', 'An issue (also called a protocol deviation) is a record that does not match a trial rule. Open a site to see what happened and the supporting evidence.'], ['3', 'Create an action plan', 'Download a draft plan for an issue. It includes a possible cause, corrective and preventive actions (CAPA), a suggested owner, and a target date.']].map(([n, title, text]) => <section className="panel guide" key={n}><span className="step">{n}</span><h2>{title}</h2><p>{text}</p></section>)}</div><section className="panel explanation"><h2>What do the labels mean?</h2><p><strong>Risk score (0–100):</strong> helps prioritize sites. A higher number means more attention is suggested; it is not a probability of harm. It combines issue frequency, severity, trend, monitoring recency, enrollment, recurrence, and query delays.</p><div className="legend">{Object.entries(bands).map(([key, text]) => <span className={'badge ' + key} key={key}>{text} · {key === 'CRITICAL' ? '75–100' : key === 'HIGH' ? '55–74.9' : key === 'MEDIUM' ? '30–54.9' : '0–29.9'}</span>)}</div><p><strong>Major / minor / administrative:</strong> indicate the type of impact assigned to a finding. A qualified reviewer should confirm severity and any proposed action.</p><p>All records in this demo are fictional. A downloaded plan is a draft, not an approved clinical decision.</p><button className="primary" onClick={() => navigate('overview')}>Go to overview <ArrowRight size={16}/></button></section></> :
      site ? <><button className="back" onClick={() => setSelected('')}><ArrowLeft size={16}/>Back to all sites</button><div className="page-heading"><p className="eyebrow">{site.site_id} · {country[site.country] || site.country}</p><h1>{site.site_name}</h1><p>{site.deviation_count} recorded issues, including {site.major_count} major issues. Review the evidence below before deciding on an action.</p></div><div className="detail-grid"><section className="panel"><span className={'badge ' + site.band}>{bands[site.band]}</span><div className="score-big">{site.score}<small> / 100 risk score</small></div><p>Last monitoring visit: <strong>{site.days_since_monitoring} days ago</strong>.</p><p className="muted">Higher scores suggest earlier review. They do not confirm that a site is unsafe.</p></section><section className="panel"><h2>Recorded issues over time</h2><p className="muted">Issue count per month. This shows recorded history, not a forecast.</p><div className="chart" role="img" aria-label={site.monthly_trend.map(p => p.month + ': ' + p.count + ' issues').join(', ')}><ResponsiveContainer width="100%" height="100%"><AreaChart data={site.monthly_trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month" tick={{ fontSize: 11 }}/><YAxis allowDecimals={false} tick={{ fontSize: 11 }}/><Tooltip/><Area name="Issues" dataKey="count" stroke="#216b55" fill="#d9eee6" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></section></div><div className="section-heading"><h2>What needs reviewing?</h2><span>{visibleIssues.length} issues</span></div>{issueCards}</> :
      page === 'overview' ? <><div className="page-heading"><p className="eyebrow">TRIAL OVERVIEW</p><h1>Know where to focus next.</h1><p>Find research sites that need attention, understand their issues, and prepare a follow-up plan.</p></div><div className="stats"><button onClick={() => { setBand(''); setSearch(''); }}><small>Research sites</small><strong>{loading ? '—' : sites.length}</strong><span>Centers included in this trial</span></button><button onClick={() => { setBand('CRITICAL'); setSearch(''); }}><small>Review first</small><strong className="red">{loading ? '—' : sites.filter(s => s.band === 'CRITICAL').length}</strong><span>{attention} sites have high or critical risk</span></button><button onClick={() => navigate('issues')}><small>Recorded issues</small><strong>{loading ? '—' : issues.length.toLocaleString()}</strong><span>All findings across every site</span></button><button onClick={() => { navigate('issues'); setSeverity('MAJOR'); }}><small>Major issues</small><strong>{loading ? '—' : major.toLocaleString()}</strong><span>Potential safety or data concerns</span></button></div>
      {!loading && sites[0] && <section className="focus-card"><div><span className="eyebrow">SUGGESTED STARTING POINT</span><h2>Review {sites[0].site_id} first</h2><p>{sites[0].major_count} major issues · {sites[0].days_since_monitoring} days since monitoring · highest risk score in this trial</p></div><button className="primary" onClick={() => openSite(sites[0].site_id)}>Review this site <ArrowRight size={17}/></button></section>}
      <section className="panel sites-panel"><div className="section-heading"><div><h2>Which sites need attention?</h2><p className="muted">Choose “View issues” to understand the problem and next steps.</p></div><span>{ranked.length} sites</span></div><div className="filters"><label className="search-label"><span>Search sites</span><div><Search size={16}/><input placeholder="Site name, ID or country" value={search} onChange={e => setSearch(e.target.value)}/></div></label><label>Priority<select value={band} onChange={e => setBand(e.target.value)}><option value="">All priorities</option>{Object.entries(bands).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</select></label><label>Sort by<select value={ascending ? 'asc' : 'desc'} onChange={e => setAscending(e.target.value === 'asc')}><option value="desc">Highest risk first</option><option value="asc">Lowest risk first</option></select></label></div>
      {loading ? <div className="empty" role="status">Loading trial data…</div> : <div className="table-wrap"><table><thead><tr><th>Research site</th><th>Priority</th><th>Risk score</th><th>Issues</th><th>Next step</th></tr></thead><tbody>{ranked.slice(0, limit).map(s => <tr key={s.site_id}><td><strong>{s.site_id}</strong><small>{s.site_name}<br/>{country[s.country] || s.country}</small></td><td><span className={'badge ' + s.band}>{bands[s.band]}</span></td><td><strong>{s.score}<span className="muted"> / 100</span></strong><div className="score-bar"><i style={{ width: s.score + '%' }}/></div></td><td><strong>{s.deviation_count} total</strong><small>{s.major_count} major</small></td><td><button className="text-button" onClick={() => openSite(s.site_id)}>View issues <ArrowRight size={15}/></button></td></tr>)}</tbody></table></div>}{!loading && !ranked.length && <div className="empty">No matching sites. Try another search or priority.</div>}{ranked.length > limit && <button className="secondary more" onClick={() => setLimit(n => n + 12)}>Show 12 more sites</button>}</section></> :
      <><div className="page-heading"><p className="eyebrow">ISSUE REVIEW</p><h1>Understand what went wrong.</h1><p>Each finding explains the mismatch, the evidence, and a suggested follow-up.</p></div><section className="panel filters"><label>Research site<select value={siteFilter} onChange={e => setSiteFilter(e.target.value)}><option value="">All sites</option>{[...sites].sort((a,b) => a.site_id.localeCompare(b.site_id)).map(s => <option key={s.site_id} value={s.site_id}>{s.site_id} · {country[s.country] || s.country}</option>)}</select></label><label>Issue severity<select value={severity} onChange={e => setSeverity(e.target.value)}><option value="">All severities</option>{Object.entries(levels).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</select></label><label>From date<input type="date" value={from} onChange={e => setFrom(e.target.value)}/></label><label>To date<input type="date" value={to} onChange={e => setTo(e.target.value)}/></label><button className="text-button" onClick={() => { setSeverity(''); setSiteFilter(''); setFrom(''); setTo(''); }}>Clear filters</button></section><p className="result-count">{loading ? 'Loading issues…' : visibleIssues.length + ' matching issues'}</p>{!loading && issueCards}</>}
      <footer>ARIP TEAM · TrialSutra <span>Synthetic demo · Action plans require human review</span></footer>
    </main>
  </div>;
}
